### ISSUE TITLE
Cased Output?

### ISSUE THREAD

**Issue by srush** [google-research-datasets/xsum_hallucination_annotations#3]
Thanks for the amazing dataset.

Was curious if you have the cased output of any of these systems?

**Comment by shashiongithub** [comment]
Thanks Sasha! 
Sorry, all models discussed in the paper were trained with uncased version of the dataset.

**Comment by srush** [comment]
Bummer, but thanks for the quick reply. 

(Hope to see you all for real in the near future🥂)
