### ISSUE TITLE
confusing ids in eval_scores data

### ISSUE THREAD

**Issue by Lukecn1** [google-research-datasets/xsum_hallucination_annotations#6]
Hi there,  

In the eval_scores_xsum_summaries data there are many instances called either "bert_withckpt" or "bert_nockpt" followed by a bbcid. These model names does not appear in the other datasets. This is currently preventing me from using your scores in a project, as I can't reliably map the scores back to the summary-article pair . 

Am I missing something, or is this a mistake? :)

**Comment by shashiongithub** [comment]
Thanks for noticing this. Please use the following mapping:

ptgen: PtGen
tconvs2s: TConvS2S
bert_nockpt: TranS2S
bert_withckpt : BERTS2S
